jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack

    - run: spack install py-nanobind cmake

    - name: build and test
      shell: spack-bash {0}
      run: |
        spack load cmake
        spack load py-nanobind
        export PYTHONPATH=$PWD/build
        cmake -S . -B build
        cmake --build build
        python -c 'import tvb_kernels as tk; print(tk)'
