name: spack
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack

    - run: spack mirror add ghcr --autopush --oci-username "${{ github.actor }}" --oci-password "${{ secrets.GITHUB_TOKEN }}" oci://ghcr.io/maedoc/tvb_kernels

    # TODO index only after building?
    - run: spack buildcache update-index ghcr

    - run: spack install cmake py-nanobind py-pytest

    - run: spack buildcache update-index ghcr

    - name: build and test
      shell: spack-bash {0}
      run: |
        spack load cmake py-nanobind py-pytest
        cmake -S . -B build
        cmake --build build
        PYTHONPATH=$PWD/build pytest tests.py
